name: TS unit tests
on: [push, pull_request]
jobs:
  bun-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bunx tsc --noEmit
      - run: bun test core
